import { useState, useMemo } from "react";
import { usePopup } from "../../contexts/PopupContext"; // Adjust path if needed based on your folder structure
import styles from "./EmojiPopup.module.css";

const EMOJI_DATA = [
  {
    category: "Popular",
    emojis: [
      { char: "👍", name: "thumbs up" },
      { char: "❤️", name: "red heart love" },
      { char: "😂", name: "face with tears of joy" },
      { char: "🔥", name: "fire hot" },
      { char: "🎉", name: "party popper celebration" },
      { char: "🥰", name: "smiling face with hearts" },
      { char: "✅", name: "check mark button" },
      { char: "😭", name: "loudly crying face" },
      { char: "🤔", name: "thinking face" },
      { char: "👀", name: "eyes" },
      { char: "🙏", name: "folded hands please thanks" },
      { char: "✨", name: "sparkles" },
      { char: "💀", name: "skull dead" },
      { char: "🤣", name: "rolling on the floor laughing" },
      { char: "📅", name: "calendar" },
      { char: "📍", name: "location pin" },
    ],
  },
  {
    category: "Smileys & Emotion",
    emojis: [
      { char: "😀", name: "grinning face happy" },
      { char: "😃", name: "grinning face with big eyes" },
      { char: "😄", name: "grinning face with smiling eyes" },
      { char: "😁", name: "beaming face with smiling eyes" },
      { char: "😆", name: "grinning squinting face" },
      { char: "😅", name: "grinning face with sweat" },
      { char: "🤣", name: "rolling on the floor laughing" },
      { char: "😂", name: "face with tears of joy" },
      { char: "🙂", name: "slightly smiling face" },
      { char: "🙃", name: "upside-down face" },
      { char: "😉", name: "winking face" },
      { char: "😊", name: "smiling face with smiling eyes" },
      { char: "😇", name: "smiling face with halo" },
      { char: "🥰", name: "smiling face with hearts love" },
      { char: "😍", name: "smiling face with heart-eyes love" },
      { char: "🤩", name: "star-struck" },
      { char: "😘", name: "face blowing a kiss" },
      { char: "😗", name: "kissing face" },
      { char: "😋", name: "face savoring food yummy" },
      { char: "😛", name: "face with tongue" },
      { char: "😜", name: "winking face with tongue" },
      { char: "🤪", name: "zany face crazy" },
      { char: "😝", name: "squinting face with tongue" },
      { char: "🤑", name: "money-mouth face" },
      { char: "🤗", name: "hugging face" },
      { char: "🤭", name: "face with hand over mouth" },
      { char: "🤫", name: "shushing face" },
      { char: "🤔", name: "thinking face" },
      { char: "🤐", name: "zipper-mouth face" },
      { char: "🤨", name: "face with raised eyebrow" },
      { char: "😐", name: "neutral face" },
      { char: "😑", name: "expressionless face" },
      { char: "😶", name: "face without mouth" },
      { char: "😏", name: "smirking face" },
      { char: "😒", name: "unamused face" },
      { char: "🙄", name: "face with rolling eyes" },
      { char: "😬", name: "grimacing face" },
      { char: "🤥", name: "lying face" },
      { char: "😌", name: "relieved face" },
      { char: "😔", name: "pensive face sad" },
      { char: "😪", name: "sleepy face" },
      { char: "🤤", name: "drooling face" },
      { char: "😴", name: "sleeping face" },
      { char: "😷", name: "face with medical mask sick" },
      { char: "🤒", name: "face with thermometer sick" },
      { char: "🤕", name: "face with head-bandage hurt" },
      { char: "🤢", name: "nauseated face vomit" },
      { char: "🤮", name: "face vomiting" },
      { char: "🤧", name: "sneezing face" },
      { char: "🥵", name: "hot face" },
      { char: "🥶", name: "cold face" },
      { char: "🥴", name: "woozy face drunk" },
      { char: "😵", name: "dizzy face" },
      { char: "🤯", name: "exploding head mind blown" },
      { char: "🤠", name: "cowboy hat face" },
      { char: "🥳", name: "partying face celebration" },
      { char: "😎", name: "smiling face with sunglasses cool" },
      { char: "🤓", name: "nerd face" },
      { char: "🧐", name: "face with monocle" },
      { char: "😕", name: "confused face" },
      { char: "😟", name: "worried face" },
      { char: "🙁", name: "slightly frowning face" },
      { char: "😮", name: "face with open mouth" },
      { char: "😯", name: "hushed face" },
      { char: "😲", name: "astonished face" },
      { char: "😳", name: "flushed face" },
      { char: "🥺", name: "pleading face" },
      { char: "😦", name: "frowning face with open mouth" },
      { char: "😧", name: "anguished face" },
      { char: "😨", name: "fearful face" },
      { char: "😰", name: "anxious face with sweat" },
      { char: "😥", name: "sad but relieved face" },
      { char: "😢", name: "crying face" },
      { char: "😭", name: "loudly crying face" },
      { char: "😱", name: "face screaming in fear" },
      { char: "😖", name: "confounded face" },
      { char: "😣", name: "persevering face" },
      { char: "😞", name: "disappointed face" },
      { char: "😓", name: "downcast face with sweat" },
      { char: "😩", name: "weary face" },
      { char: "😫", name: "tired face" },
      { char: "🥱", name: "yawning face" },
      { char: "😤", name: "face with steam from nose angry" },
      { char: "😡", name: "pouting face angry" },
      { char: "😠", name: "angry face" },
      { char: "🤬", name: "face with symbols on mouth curse" },
      { char: "😈", name: "smiling face with horns devil" },
      { char: "👿", name: "angry face with horns devil" },
      { char: "💀", name: "skull dead" },
      { char: "☠️", name: "skull and crossbones" },
      { char: "💩", name: "pile of poo" },
      { char: "🤡", name: "clown face" },
      { char: "👻", name: "ghost" },
      { char: "👽", name: "alien" },
    ],
  },
  {
    category: "People & Body",
    emojis: [
      { char: "👋", name: "waving hand" },
      { char: "🤚", name: "raised back of hand" },
      { char: "🖐️", name: "hand with fingers splayed" },
      { char: "✋", name: "raised hand" },
      { char: "🖖", name: "vulcan salute" },
      { char: "👌", name: "OK hand" },
      { char: "🤏", name: "pinching hand" },
      { char: "✌️", name: "victory hand peace" },
      { char: "🤞", name: "crossed fingers luck" },
      { char: "🤟", name: "love-you gesture" },
      { char: "🤘", name: "sign of the horns rock" },
      { char: "🤙", name: "call me hand" },
      { char: "👈", name: "backhand index pointing left" },
      { char: "👉", name: "backhand index pointing right" },
      { char: "👆", name: "backhand index pointing up" },
      { char: "🖕", name: "middle finger" },
      { char: "👇", name: "backhand index pointing down" },
      { char: "☝️", name: "index pointing up" },
      { char: "👍", name: "thumbs up" },
      { char: "👎", name: "thumbs down" },
      { char: "✊", name: "raised fist" },
      { char: "👊", name: "oncoming fist" },
      { char: "🤛", name: "left-facing fist" },
      { char: "🤜", name: "right-facing fist" },
      { char: "👏", name: "clapping hands" },
      { char: "🙌", name: "raising hands" },
      { char: "👐", name: "open hands" },
      { char: "🤲", name: "palms up together" },
      { char: "🤝", name: "handshake" },
      { char: "🙏", name: "folded hands pray" },
      { char: "💅", name: "nail polish" },
      { char: "🤳", name: "selfie" },
      { char: "💪", name: "flexed biceps strong" },
      { char: "🧠", name: "brain" },
      { char: "🦷", name: "tooth" },
      { char: "🦴", name: "bone" },
      { char: "👀", name: "eyes" },
      { char: "👁️", name: "eye" },
      { char: "💋", name: "kiss mark" },
      { char: "👶", name: "baby" },
      { char: "👧", name: "girl" },
      { char: "🧒", name: "child" },
      { char: "👦", name: "boy" },
      { char: "👩", name: "woman" },
      { char: "🧑", name: "person" },
      { char: "👨", name: "man" },
      { char: "🧔", name: "person with beard" },
      { char: "👵", name: "old woman" },
      { char: "🧓", name: "older person" },
      { char: "👴", name: "old man" },
      { char: "👮", name: "police officer" },
      { char: "👷", name: "construction worker" },
      { char: "💂", name: "guard" },
      { char: "🕵️", name: "detective" },
      { char: "👩‍⚕️", name: "woman health worker doctor" },
      { char: "👨‍⚕️", name: "man health worker doctor" },
      { char: "👩‍🎓", name: "woman student" },
      { char: "👨‍🎓", name: "man student" },
      { char: "👩‍🏫", name: "woman teacher" },
      { char: "👨‍🏫", name: "man teacher" },
      { char: "👩‍⚖️", name: "woman judge" },
      { char: "👨‍⚖️", name: "man judge" },
      { char: "👩‍🌾", name: "woman farmer" },
      { char: "👨‍🌾", name: "man farmer" },
      { char: "👩‍🍳", name: "woman cook chef" },
      { char: "👨‍🍳", name: "man cook chef" },
      { char: "👩‍🔧", name: "woman mechanic" },
      { char: "👨‍🔧", name: "man mechanic" },
      { char: "👩‍🏭", name: "woman factory worker" },
      { char: "👨‍🏭", name: "man factory worker" },
      { char: "👩‍💼", name: "woman office worker" },
      { char: "👨‍💼", name: "man office worker" },
      { char: "👩‍🔬", name: "woman scientist" },
      { char: "👨‍🔬", name: "man scientist" },
      { char: "👩‍💻", name: "woman technologist" },
      { char: "👨‍💻", name: "man technologist" },
      { char: "👩‍🎤", name: "woman singer" },
      { char: "👨‍🎤", name: "man singer" },
      { char: "👩‍🎨", name: "woman artist" },
      { char: "👨‍🎨", name: "man artist" },
      { char: "👩‍✈️", name: "woman pilot" },
      { char: "👨‍✈️", name: "man pilot" },
      { char: "👩‍🚀", name: "woman astronaut" },
      { char: "👨‍🚀", name: "man astronaut" },
      { char: "👩‍🚒", name: "woman firefighter" },
      { char: "👨‍🚒", name: "man firefighter" },
      { char: "🧛", name: "vampire" },
      { char: "🧟", name: "zombie" },
      { char: "🧞", name: "genie" },
      { char: "🧜", name: "mermaid" },
    ],
  },
  {
    category: "Animals & Nature",
    emojis: [
      { char: "🐶", name: "dog face" },
      { char: "🐱", name: "cat face" },
      { char: "🐭", name: "mouse face" },
      { char: "🐹", name: "hamster face" },
      { char: "🐰", name: "rabbit face" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger face" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow face" },
      { char: "🐷", name: "pig face" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey face" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "baby chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse face" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "honeybee" },
      { char: "🐛", name: "bug" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🦖", name: "T-Rex dinosaur" },
      { char: "🦕", name: "sauropod dinosaur" },
      { char: "🐙", name: "octopus" },
      { char: "🦑", name: "squid" },
      { char: "🦐", name: "shrimp" },
      { char: "🦞", name: "lobster" },
      { char: "🦀", name: "crab" },
      { char: "🐡", name: "blowfish" },
      { char: "🐠", name: "tropical fish" },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "spouting whale" },
      { char: "🐋", name: "whale" },
      { char: "🦈", name: "shark" },
      { char: "💐", name: "bouquet flowers" },
      { char: "🌸", name: "cherry blossom" },
      { char: "💮", name: "white flower" },
      { char: "🌹", name: "rose" },
      { char: "🥀", name: "wilted flower" },
      { char: "🌺", name: "hibiscus" },
      { char: "🌻", name: "sunflower" },
      { char: "🌼", name: "blossom" },
      { char: "🌷", name: "tulip" },
      { char: "🌱", name: "seedling" },
      { char: "🌲", name: "evergreen tree" },
      { char: "🌳", name: "deciduous tree" },
      { char: "🌴", name: "palm tree" },
      { char: "🌵", name: "cactus" },
      { char: "🌾", name: "sheaf of rice" },
      { char: "🌿", name: "herb" },
      { char: "🍀", name: "four leaf clover luck" },
      { char: "🍁", name: "maple leaf" },
      { char: "🍂", name: "fallen leaf" },
      { char: "🍃", name: "leaf fluttering in wind" },
    ],
  },
  {
    category: "Food & Drink",
    emojis: [
      { char: "🍇", name: "grapes" },
      { char: "🍈", name: "melon" },
      { char: "🍉", name: "watermelon" },
      { char: "🍊", name: "tangerine" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍍", name: "pineapple" },
      { char: "🥭", name: "mango" },
      { char: "🍎", name: "red apple" },
      { char: "🍏", name: "green apple" },
      { char: "🍐", name: "pear" },
      { char: "🍑", name: "peach" },
      { char: "🍒", name: "cherries" },
      { char: "🍓", name: "strawberry" },
      { char: "🥝", name: "kiwi fruit" },
      { char: "🍅", name: "tomato" },
      { char: "🥥", name: "coconut" },
      { char: "🥑", name: "avocado" },
      { char: "🍆", name: "eggplant" },
      { char: "🥔", name: "potato" },
      { char: "🥕", name: "carrot" },
      { char: "🌽", name: "corn" },
      { char: "🌶️", name: "hot pepper" },
      { char: "🥒", name: "cucumber" },
      { char: "🥦", name: "broccoli" },
      { char: "🧄", name: "garlic" },
      { char: "🧅", name: "onion" },
      { char: "🍄", name: "mushroom" },
      { char: "🍞", name: "bread" },
      { char: "🥐", name: "croissant" },
      { char: "🥖", name: "baguette bread" },
      { char: "🥨", name: "pretzel" },
      { char: "🥯", name: "bagel" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🧀", name: "cheese wedge" },
      { char: "🍖", name: "meat on bone" },
      { char: "🍗", name: "poultry leg" },
      { char: "🥩", name: "cut of meat steak" },
      { char: "🥓", name: "bacon" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "french fries" },
      { char: "🍕", name: "pizza" },
      { char: "🌭", name: "hot dog" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "cooking" },
      { char: "🥘", name: "shallow pan of food" },
      { char: "🍲", name: "pot of food" },
      { char: "🥣", name: "bowl with spoon" },
      { char: "🥗", name: "green salad" },
      { char: "🍿", name: "popcorn" },
      { char: "🧂", name: "salt" },
      { char: "🥫", name: "canned food" },
      { char: "🍱", name: "bento box" },
      { char: "🍘", name: "rice cracker" },
      { char: "🍙", name: "rice ball" },
      { char: "🍚", name: "cooked rice" },
      { char: "🍛", name: "curry rice" },
      { char: "🍜", name: "steaming bowl noodle" },
      { char: "🍝", name: "spaghetti" },
      { char: "🍠", name: "roasted sweet potato" },
      { char: "🍢", name: "oden" },
      { char: "🍣", name: "sushi" },
      { char: "🍤", name: "fried shrimp" },
      { char: "🍥", name: "fish cake with swirl" },
      { char: "🥮", name: "moon cake" },
      { char: "🍡", name: "dango" },
      { char: "🥟", name: "dumpling" },
      { char: "🥠", name: "fortune cookie" },
      { char: "🥡", name: "takeout box" },
      { char: "🍦", name: "soft ice cream" },
      { char: "🍧", name: "shaved ice" },
      { char: "🍨", name: "ice cream" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍰", name: "shortcake" },
      { char: "🧁", name: "cupcake" },
      { char: "🥧", name: "pie" },
      { char: "🍫", name: "chocolate bar" },
      { char: "🍬", name: "candy" },
      { char: "🍭", name: "lollipop" },
      { char: "🍮", name: "custard" },
      { char: "🍯", name: "honey pot" },
      { char: "🍼", name: "baby bottle" },
      { char: "🥛", name: "glass of milk" },
      { char: "☕", name: "hot beverage coffee" },
      { char: "🍵", name: "teacup without handle" },
      { char: "🍶", name: "sake" },
      { char: "🍾", name: "bottle with popping cork" },
      { char: "🍷", name: "wine glass" },
      { char: "🍸", name: "cocktail glass" },
      { char: "🍹", name: "tropical drink" },
      { char: "🍺", name: "beer mug" },
      { char: "🍻", name: "clinking beer mugs" },
      { char: "🥂", name: "clinking glasses" },
      { char: "🥃", name: "tumbler glass whiskey" },
      { char: "🥤", name: "cup with straw" },
      { char: "🧃", name: "beverage box" },
      { char: "🧉", name: "mate" },
      { char: "🧊", name: "ice" },
    ],
  },
  {
    category: "Activities & Objects",
    emojis: [
      { char: "🎉", name: "party popper" },
      { char: "🎈", name: "balloon" },
      { char: "🎁", name: "wrapped gift" },
      { char: "🏆", name: "trophy" },
      { char: "🥇", name: "1st place medal" },
      { char: "🥈", name: "2nd place medal" },
      { char: "🥉", name: "3rd place medal" },
      { char: "⚽", name: "soccer ball" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "american football" },
      { char: "⚾", name: "baseball" },
      { char: "🥎", name: "softball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🏉", name: "rugby football" },
      { char: "🎱", name: "pool 8 ball" },
      { char: "🏓", name: "ping pong" },
      { char: "🏸", name: "badminton" },
      { char: "🥊", name: "boxing glove" },
      { char: "🥋", name: "martial arts uniform" },
      { char: "🥅", name: "goal net" },
      { char: "⛳", name: "flag in hole golf" },
      { char: "⛸️", name: "ice skate" },
      { char: "🎣", name: "fishing pole" },
      { char: "🤿", name: "diving mask" },
      { char: "🎿", name: "skis" },
      { char: "🛷", name: "sled" },
      { char: "🥌", name: "curling stone" },
      { char: "🎯", name: "bullseye dart" },
      { char: "🪁", name: "kite" },
      { char: "🔫", name: "water pistol gun" },
      { char: "🎱", name: "billiards" },
      { char: "🔮", name: "crystal ball" },
      { char: "🎮", name: "video game" },
      { char: "🕹️", name: "joystick" },
      { char: "🎰", name: "slot machine" },
      { char: "🎲", name: "game die" },
      { char: "🧩", name: "puzzle piece" },
      { char: "🧸", name: "teddy bear" },
      { char: "🎨", name: "artist palette" },
      { char: "🧶", name: "yarn" },
      { char: "🧵", name: "thread" },
      { char: "👓", name: "glasses" },
      { char: "🕶️", name: "sunglasses" },
      { char: "🥽", name: "goggles" },
      { char: "🥼", name: "lab coat" },
      { char: "🦺", name: "safety vest" },
      { char: "👔", name: "necktie" },
      { char: "👕", name: "t-shirt" },
      { char: "👖", name: "jeans" },
      { char: "🧣", name: "scarf" },
      { char: "🧤", name: "gloves" },
      { char: "🧥", name: "coat" },
      { char: "🧦", name: "socks" },
      { char: "👗", name: "dress" },
      { char: "👘", name: "kimono" },
      { char: "👙", name: "bikini" },
      { char: "👚", name: "woman's clothes" },
      { char: "👛", name: "purse" },
      { char: "👜", name: "handbag" },
      { char: "🎒", name: "backpack" },
      { char: "👞", name: "shoe" },
      { char: "👟", name: "running shoe" },
      { char: "🥾", name: "hiking boot" },
      { char: "👠", name: "high-heeled shoe" },
      { char: "👡", name: "sandal" },
      { char: "👢", name: "woman's boot" },
      { char: "👑", name: "crown" },
      { char: "👒", name: "woman's hat" },
      { char: "🎩", name: "top hat" },
      { char: "🎓", name: "graduation cap" },
      { char: "🧢", name: "billed cap" },
      { char: "⛑️", name: "rescue worker's helmet" },
      { char: "💄", name: "lipstick" },
      { char: "💍", name: "ring" },
      { char: "💎", name: "gem stone" },
      { char: "🔇", name: "muted speaker" },
      { char: "🔈", name: "speaker low volume" },
      { char: "🔉", name: "speaker medium volume" },
      { char: "🔊", name: "speaker high volume" },
      { char: "📢", name: "loudspeaker" },
      { char: "📣", name: "megaphone" },
      { char: "📯", name: "postal horn" },
      { char: "🔔", name: "bell" },
      { char: "🔕", name: "bell with slash" },
      { char: "🎼", name: "musical score" },
      { char: "🎵", name: "musical note" },
      { char: "🎶", name: "musical notes" },
      { char: "🎙️", name: "studio microphone" },
      { char: "🎚️", name: "level slider" },
      { char: "🎛️", name: "control knobs" },
      { char: "🎤", name: "microphone" },
      { char: "🎧", name: "headphone" },
      { char: "📻", name: "radio" },
      { char: "🎷", name: "saxophone" },
      { char: "🎸", name: "guitar" },
      { char: "🎹", name: "musical keyboard" },
      { char: "🎺", name: "trumpet" },
      { char: "🎻", name: "violin" },
      { char: "🪕", name: "banjo" },
      { char: "🥁", name: "drum" },
      { char: "📱", name: "mobile phone" },
      { char: "📲", name: "mobile phone with arrow" },
      { char: "☎️", name: "telephone" },
      { char: "📞", name: "telephone receiver" },
      { char: "📠", name: "fax machine" },
      { char: "🔋", name: "battery" },
      { char: "🔌", name: "electric plug" },
      { char: "💻", name: "laptop" },
      { char: "🖥️", name: "desktop computer" },
      { char: "🖨️", name: "printer" },
      { char: "⌨️", name: "keyboard" },
      { char: "🖱️", name: "computer mouse" },
      { char: "🖲️", name: "trackball" },
      { char: "💽", name: "computer disk" },
      { char: "💾", name: "floppy disk" },
      { char: "💿", name: "optical disk" },
      { char: "📀", name: "dvd" },
      { char: "🎥", name: "movie camera" },
      { char: "🎞️", name: "film frames" },
      { char: "📽️", name: "film projector" },
      { char: "🎬", name: "clapper board" },
      { char: "📺", name: "television" },
      { char: "📷", name: "camera" },
      { char: "📸", name: "camera with flash" },
      { char: "📹", name: "video camera" },
      { char: "📼", name: "videocassette" },
      { char: "🔍", name: "magnifying glass left" },
      { char: "🔎", name: "magnifying glass right" },
      { char: "🕯️", name: "candle" },
      { char: "💡", name: "light bulb" },
      { char: "🔦", name: "flashlight" },
      { char: "🏮", name: "red paper lantern" },
      { char: "📔", name: "notebook with decorative cover" },
      { char: "📕", name: "closed book" },
      { char: "📖", name: "open book" },
      { char: "📗", name: "green book" },
      { char: "📘", name: "blue book" },
      { char: "📙", name: "orange book" },
      { char: "📚", name: "books" },
      { char: "📓", name: "notebook" },
      { char: "📒", name: "ledger" },
      { char: "📃", name: "page with curl" },
      { char: "📜", name: "scroll" },
      { char: "📄", name: "page facing up" },
      { char: "📰", name: "newspaper" },
      { char: "🗞️", name: "rolled-up newspaper" },
      { char: "📑", name: "bookmark tabs" },
      { char: "🔖", name: "bookmark" },
      { char: "🏷️", name: "label" },
      { char: "💰", name: "money bag" },
      { char: "💴", name: "yen banknote" },
      { char: "💵", name: "dollar banknote" },
      { char: "💶", name: "euro banknote" },
      { char: "💷", name: "pound banknote" },
      { char: "💸", name: "money with wings" },
      { char: "💳", name: "credit card" },
      { char: "🧾", name: "receipt" },
      { char: "✉️", name: "envelope" },
      { char: "📧", name: "e-mail" },
      { char: "📨", name: "incoming envelope" },
      { char: "📩", name: "envelope with arrow" },
      { char: "📤", name: "outbox tray" },
      { char: "📥", name: "inbox tray" },
      { char: "📦", name: "package" },
      { char: "📫", name: "closed mailbox with raised flag" },
      { char: "📪", name: "closed mailbox with lowered flag" },
      { char: "📬", name: "open mailbox with raised flag" },
      { char: "📭", name: "open mailbox with lowered flag" },
      { char: "📮", name: "postbox" },
      { char: "🗳️", name: "ballot box with ballot" },
      { char: "✏️", name: "pencil" },
      { char: "✒️", name: "black nib" },
      { char: "🖋️", name: "fountain pen" },
      { char: "🖊️", name: "pen" },
      { char: "🖌️", name: "paintbrush" },
      { char: "🖍️", name: "crayon" },
      { char: "📝", name: "memo" },
      { char: "💼", name: "briefcase" },
      { char: "📁", name: "file folder" },
      { char: "📂", name: "open file folder" },
      { char: "🗂️", name: "card index dividers" },
      { char: "📅", name: "calendar" },
      { char: "📆", name: "tear-off calendar" },
      { char: "🗒️", name: "spiral notepad" },
      { char: "🗓️", name: "spiral calendar" },
      { char: "📇", name: "card index" },
      { char: "📈", name: "chart increasing" },
      { char: "📉", name: "chart decreasing" },
      { char: "📊", name: "bar chart" },
      { char: "📋", name: "clipboard" },
      { char: "📌", name: "pushpin" },
      { char: "📍", name: "round pushpin" },
      { char: "📎", name: "paperclip" },
      { char: "🖇️", name: "linked paperclips" },
      { char: "📏", name: "straight ruler" },
      { char: "📐", name: "triangular ruler" },
      { char: "✂️", name: "scissors" },
      { char: "🗃️", name: "card file box" },
      { char: "🗄️", name: "file cabinet" },
      { char: "🗑️", name: "wastebasket" },
      { char: "🔒", name: "locked" },
      { char: "🔓", name: "unlocked" },
      { char: "🔏", name: "locked with pen" },
      { char: "🔐", name: "locked with key" },
      { char: "🔑", name: "key" },
      { char: "🗝️", name: "old key" },
      { char: "🔨", name: "hammer" },
      { char: "🪓", name: "axe" },
      { char: "⛏️", name: "pick" },
      { char: "⚒️", name: "hammer and pick" },
      { char: "🛠️", name: "hammer and wrench" },
      { char: "🗡️", name: "dagger" },
      { char: "⚔️", name: "crossed swords" },
      { char: "🔫", name: "pistol" },
      { char: "🏹", name: "bow and arrow" },
      { char: "🛡️", name: "shield" },
      { char: "🔧", name: "wrench" },
      { char: "🔩", name: "nut and bolt" },
      { char: "⚙️", name: "gear" },
      { char: "🗜️", name: "clamp" },
      { char: "⚖️", name: "balance scale" },
      { char: "🦯", name: "probing cane" },
      { char: "🔗", name: "link" },
      { char: "⛓️", name: "chains" },
      { char: "🧰", name: "toolbox" },
      { char: "🧲", name: "magnet" },
      { char: "⚗️", name: "alembic" },
      { char: "🧪", name: "test tube" },
      { char: "🧫", name: "petri dish" },
      { char: "🧬", name: "dna" },
      { char: "🔬", name: "microscope" },
      { char: "🔭", name: "telescope" },
      { char: "📡", name: "satellite antenna" },
      { char: "💉", name: "syringe" },
      { char: "🩸", name: "drop of blood" },
      { char: "💊", name: "pill" },
      { char: "🩹", name: "adhesive bandage" },
      { char: "🩺", name: "stethoscope" },
      { char: "🚪", name: "door" },
      { char: "🛏️", name: "bed" },
      { char: "🛋️", name: "couch and lamp" },
      { char: "🪑", name: "chair" },
      { char: "🚽", name: "toilet" },
      { char: "🚿", name: "shower" },
      { char: "🛁", name: "bathtub" },
      { char: "🪒", name: "razor" },
      { char: "🧴", name: "lotion bottle" },
      { char: "🧷", name: "safety pin" },
      { char: "🧹", name: "broom" },
      { char: "🧺", name: "basket" },
      { char: "🧻", name: "roll of paper" },
      { char: "🧼", name: "soap" },
      { char: "🧽", name: "sponge" },
      { char: "🧯", name: "fire extinguisher" },
      { char: "🛒", name: "shopping cart" },
    ],
  },
  {
    category: "Travel & Places",
    emojis: [
      { char: "🌍", name: "globe showing Europe-Africa" },
      { char: "🌎", name: "globe showing Americas" },
      { char: "🌏", name: "globe showing Asia-Australia" },
      { char: "🗺️", name: "world map" },
      { char: "🗾", name: "map of Japan" },
      { char: "🏔️", name: "snow-capped mountain" },
      { char: "⛰️", name: "mountain" },
      { char: "🌋", name: "volcano" },
      { char: "🗻", name: "mount fuji" },
      { char: "🏕️", name: "camping" },
      { char: "🏖️", name: "beach with umbrella" },
      { char: "🏜️", name: "desert" },
      { char: "🏝️", name: "desert island" },
      { char: "🏞️", name: "national park" },
      { char: "🏟️", name: "stadium" },
      { char: "🏛️", name: "classical building" },
      { char: "🏗️", name: "building construction" },
      { char: "🧱", name: "brick" },
      { char: "🏘️", name: "houses" },
      { char: "🏚️", name: "derelict house" },
      { char: "🏠", name: "house" },
      { char: "🏡", name: "house with garden" },
      { char: "🏢", name: "office building" },
      { char: "🏣", name: "Japanese post office" },
      { char: "🏤", name: "post office" },
      { char: "🏥", name: "hospital" },
      { char: "🏦", name: "bank" },
      { char: "🏨", name: "hotel" },
      { char: "🏩", name: "love hotel" },
      { char: "🏪", name: "convenience store" },
      { char: "🏫", name: "school" },
      { char: "🏬", name: "department store" },
      { char: "🏭", name: "factory" },
      { char: "🏯", name: "Japanese castle" },
      { char: "🏰", name: "castle" },
      { char: "💒", name: "wedding" },
      { char: "🗼", name: "Tokyo tower" },
      { char: "🗽", name: "Statue of Liberty" },
      { char: "⛪", name: "church" },
      { char: "🕌", name: "mosque" },
      { char: "🛕", name: "hindu temple" },
      { char: "🕍", name: "synagogue" },
      { char: "⛩️", name: "shinto shrine" },
      { char: "🕋", name: "kaaba" },
      { char: "⛲", name: "fountain" },
      { char: "⛺", name: "tent" },
      { char: "🌁", name: "foggy" },
      { char: "🌃", name: "night with stars" },
      { char: "🏙️", name: "cityscape" },
      { char: "🌄", name: "sunrise over mountains" },
      { char: "🌅", name: "sunrise" },
      { char: "🌆", name: "cityscape at dusk" },
      { char: "🌇", name: "sunset" },
      { char: "🌉", name: "bridge at night" },
      { char: "🎠", name: "carousel horse" },
      { char: "🎡", name: "ferris wheel" },
      { char: "🎢", name: "roller coaster" },
      { char: "🚂", name: "locomotive" },
      { char: "🚃", name: "railway car" },
      { char: "🚄", name: "high-speed train" },
      { char: "🚅", name: "bullet train" },
      { char: "🚆", name: "train" },
      { char: "🚇", name: "metro" },
      { char: "🚈", name: "light rail" },
      { char: "🚉", name: "station" },
      { char: "🚊", name: "tram" },
      { char: "🚝", name: "monorail" },
      { char: "🚞", name: "mountain railway" },
      { char: "🚋", name: "tram car" },
      { char: "🚌", name: "bus" },
      { char: "🚍", name: "oncoming bus" },
      { char: "🚎", name: "trolleybus" },
      { char: "🚐", name: "minibus" },
      { char: "🚑", name: "ambulance" },
      { char: "🚒", name: "fire engine" },
      { char: "🚓", name: "police car" },
      { char: "🚔", name: "oncoming police car" },
      { char: "🚕", name: "taxi" },
      { char: "🚖", name: "oncoming taxi" },
      { char: "🚗", name: "automobile car" },
      { char: "🚘", name: "oncoming automobile" },
      { char: "🚙", name: "sport utility vehicle" },
      { char: "🚚", name: "delivery truck" },
      { char: "🚛", name: "articulated lorry" },
      { char: "🚜", name: "tractor" },
      { char: "🏎️", name: "racing car" },
      { char: "🏍️", name: "motorcycle" },
      { char: "🛵", name: "motor scooter" },
      { char: "🦽", name: "manual wheelchair" },
      { char: "🦼", name: "motorized wheelchair" },
      { char: "🛺", name: "auto rickshaw" },
      { char: "🚲", name: "bicycle" },
      { char: "🛴", name: "kick scooter" },
      { char: "🛹", name: "skateboard" },
      { char: "🚏", name: "bus stop" },
      { char: "🛣️", name: "motorway" },
      { char: "🛤️", name: "railway track" },
      { char: "⛽", name: "fuel pump" },
      { char: "🚨", name: "police car light" },
      { char: "🚥", name: "horizontal traffic light" },
      { char: "🚦", name: "vertical traffic light" },
      { char: "🚧", name: "construction" },
      { char: "⚓", name: "anchor" },
      { char: "⛵", name: "sailboat" },
      { char: "🛶", name: "canoe" },
      { char: "🚤", name: "speedboat" },
      { char: "🛳️", name: "passenger ship" },
      { char: "⛴️", name: "ferry" },
      { char: "🛥️", name: "motor boat" },
      { char: "🚢", name: "ship" },
      { char: "✈️", name: "airplane" },
      { char: "🛩️", name: "small airplane" },
      { char: "🛫", name: "airplane departure" },
      { char: "🛬", name: "airplane arrival" },
      { char: "🪂", name: "parachute" },
      { char: "💺", name: "seat" },
      { char: "🚁", name: "helicopter" },
      { char: "🚟", name: "suspension railway" },
      { char: "🚠", name: "mountain cableway" },
      { char: "🚡", name: "aerial tramway" },
      { char: "🛰️", name: "satellite" },
      { char: "🚀", name: "rocket" },
      { char: "🛸", name: "flying saucer" },
    ],
  },
  {
    category: "Symbols & Flags",
    emojis: [
      { char: "❤️", name: "red heart love" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "🤎", name: "brown heart" },
      { char: "💔", name: "broken heart" },
      { char: "❣️", name: "heart exclamation" },
      { char: "💕", name: "two hearts" },
      { char: "💞", name: "revolving hearts" },
      { char: "💓", name: "beating heart" },
      { char: "💗", name: "growing heart" },
      { char: "💖", name: "sparkling heart" },
      { char: "💘", name: "heart with arrow" },
      { char: "💝", name: "heart with ribbon" },
      { char: "💯", name: "hundred points" },
      { char: "💢", name: "anger symbol" },
      { char: "💥", name: "collision" },
      { char: "💫", name: "dizzy" },
      { char: "💦", name: "sweat droplets" },
      { char: "💨", name: "dashing away" },
      { char: "🕳️", name: "hole" },
      { char: "💣", name: "bomb" },
      { char: "💬", name: "speech balloon" },
      { char: "👁️‍🗨️", name: "eye in speech bubble" },
      { char: "🗨️", name: "left speech bubble" },
      { char: "🗯️", name: "right anger bubble" },
      { char: "💭", name: "thought balloon" },
      { char: "💤", name: "zzz sleep" },
      { char: "👋", name: "waving hand" },
      { char: "🛑", name: "stop sign" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "glowing star" },
      { char: "✨", name: "sparkles" },
      { char: "⚡", name: "high voltage" },
      { char: "☄️", name: "comet" },
      { char: "🔥", name: "fire" },
      { char: "💧", name: "droplet" },
      { char: "🌊", name: "water wave" },
      { char: "🎃", name: "jack-o-lantern" },
      { char: "🎄", name: "Christmas tree" },
      { char: "🎆", name: "fireworks" },
      { char: "🎇", name: "sparkler" },
      { char: "🧨", name: "firecracker" },
      { char: "🎈", name: "balloon" },
      { char: "🎉", name: "party popper" },
      { char: "🎊", name: "confetti ball" },
      { char: "🎋", name: "tanabata tree" },
      { char: "🎍", name: "pine decoration" },
      { char: "🎎", name: "Japanese dolls" },
      { char: "🎏", name: "carp streamer" },
      { char: "🎐", name: "wind chime" },
      { char: "🎑", name: "moon viewing ceremony" },
      { char: "🧧", name: "red envelope" },
      { char: "🎀", name: "ribbon" },
      { char: "🎁", name: "wrapped gift" },
      { char: "🎗️", name: "reminder ribbon" },
      { char: "🎟️", name: "admission tickets" },
      { char: "🎫", name: "ticket" },
      { char: "⛔", name: "no entry" },
      { char: "🚫", name: "prohibited" },
      { char: "🚳", name: "no bicycles" },
      { char: "🚭", name: "no smoking" },
      { char: "🚯", name: "no littering" },
      { char: "🚱", name: "non-potable water" },
      { char: "🚷", name: "no pedestrians" },
      { char: "📵", name: "no mobile phones" },
      { char: "🔞", name: "no one under eighteen" },
      { char: "⚠️", name: "warning" },
      { char: "✅", name: "check mark button" },
      { char: "✔️", name: "check mark" },
      { char: "❎", name: "cross mark button" },
      { char: "❌", name: "cross mark" },
      { char: "❔", name: "white question mark" },
      { char: "❓", name: "question mark" },
      { char: "❕", name: "white exclamation mark" },
      { char: "❗", name: "exclamation mark" },
      { char: "🏁", name: "chequered flag" },
      { char: "🚩", name: "triangular flag" },
      { char: "🎌", name: "crossed flags" },
      { char: "🏴", name: "black flag" },
      { char: "🏳️", name: "white flag" },
      { char: "🏳️‍🌈", name: "rainbow flag" },
      { char: "🏳️‍⚧️", name: "transgender flag" },
      { char: "🏴‍☠️", name: "pirate flag" },
    ],
  },
];

export default function EmojiPopup({ handleEmojiChange }) {
  const [search, setSearch] = useState("");
  const { closePopup } = usePopup();

  const filteredCategories = useMemo(() => {
    const lowerSearch = search.toLowerCase();
    if (!lowerSearch) return EMOJI_DATA;

    // Filter emojis within categories, and only keep categories that have matching emojis
    return EMOJI_DATA.map((category) => ({
      ...category,
      emojis: category.emojis.filter(
        (item) =>
          item.name.includes(lowerSearch) || item.char.includes(lowerSearch),
      ),
    })).filter((category) => category.emojis.length > 0);
  }, [search]);

  return (
    <div className={styles.emojiPopupContainer}>
      <div className={styles.searchContainer}>
        <input
          type="text"
          placeholder="Search emojis..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          autoFocus
        />
      </div>
      <div className={`${styles.emojiList} default-scrollbar`}>
        {filteredCategories.length > 0 ? (
          filteredCategories.map((cat, index) => (
            <div key={index} className={styles.categorySection}>
              <div className={styles.categoryTitle}>{cat.category}</div>
              <div className={styles.grid}>
                {cat.emojis.map((item, idx) => (
                  <button
                    key={`${index}-${idx}`}
                    className={styles.emojiBtn}
                    onClick={() => {
                      handleEmojiChange(item.char);
                      closePopup();
                    }}
                    title={item.name}
                  >
                    <p>{item.char}</p>
                  </button>
                ))}
              </div>
            </div>
          ))
        ) : (
          <p className={styles.emptyState}>No emojis found</p>
        )}
      </div>
    </div>
  );
}
